
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: scope
    value: "ManagementGroup"
  - name: scopeName
    value: "324f7296-1869-4489-b11e-912351f38ead"
  - name: folder
    value: "./policies/deploy"

steps:
- task: AzurePowerShell@5
  inputs:
    displayName: 'Deploy Azure Policy Definitions'
    azureSubscription: 'Root Management Group Connection'
    ScriptType: 'FilePath'
    ScriptPath: './scripts/azpolicy.ps1'
    ScriptArguments: '-Scope "$(scope)" -ScopeName "$(scopeName)" -PolicyFolder "$(folder)"'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
