trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: bicepFolder
    value: "./bicepInstall"
  - name: bicepPath
    value: "./templatespec/avd/avd"
  - name: fileName
    value: "avd"
  - name: serviceConnection
    value: "az-platform-connection"
  - name: specName
    value: "az-tempspec-avd"
  - name: resourceGroup
    value: "mpn-rg-templates"
  - name: subscription
    value: "1fd221fd-5347-47fa-9fd6-fb4fa7f31251"


stages:
  - template: templates/stages-specs.yml
    parameters:
      bicepPath: '$(bicepPath)'
      bicepFolder: '$(bicepFolder)'
      fileName: '$(fileName)'
      serviceConnection: '$(serviceConnection)'
      specName: '$(specName)'
      resourceGroup: '$(resourceGroup)'
      subscription: '$(subscription)'