trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: bicepFolder
    value: "$(Build.Repository.LocalPath)/bicepInstall"
  - name: bicepPath
    value: "$(Build.Repository.LocalPath)/templatespec/internalappservice"
  - name: fileName
    value: "internalappservice"
  - name: serviceConnection
    value: "az-platform"
  - name: specName
    value: "az-tempspec-internalappservice"
  - name: resourceGroup
    value: "gaag-rg-templates"
  - name: subscription
    value: "5b389701-0e47-4738-b4fe-ddb67ac3a036"

extends:
  template: templates/stages-specs.yml
  parameters:
    bicepPath: '$(bicepPath)'
    bicepFolder: '$(bicepFolder)'
    fileName: '$(fileName)'
    serviceConnection: '$(serviceConnection)'
    specName: '$(specName)'
    resourceGroup: '$(resourceGroup)'
    subscription: '$(subscription)'