name: "Deploy Template Spec"
description: "Composite actions for deploying a template spec."
inputs:
  clientId:
    description: 'Application client ID'
    required: true
  clientSecret:
    description: 'Application client Secret'
    required: true
  tenantId:
    description: 'Application tenant Id'
    required: true
  azureSubscription:
    description: 'Subscription'
    required: true
  specFolder:
    description: 'Specification folder'
    required: true
  specName:
    description: 'Specification name'
    required: true
  secret:
    description: 'Azure Secret'
    required: true
  resourceGroup:
    description: 'Name of the resource group'
    required: true
  specFileName:
    description: 'The files name of the spec'
    required: true
runs:
  using: "composite"
  steps:
       - uses: actions/download-artifact@v2
         name: Download template spec
         with:
             name: ${{inputs.specName}}
       - uses: actions/download-artifact@v2
         name: Download utility scripts
         with:
             name: ps-${{inputs.specName}}
       - name: Azure Login
         uses: Azure/login@v1
         with:
           creds: '{"clientId":"${{ inputs.clientId }}","clientSecret":"${{ inputs.clientSecret }}","subscriptionId":"${{ inputs.azureSubscription }}","tenantId":"${{ inputs.tenantId }}"}'
           enable-AzPSSession: true
       - name: Check versionnumber
         uses: azure/powershell@v1
         id: calculate
         with:
           inlineScript: |
              .\Get-TemplateSpecVersion.ps1 -TemplateSpecName "${{env.specName}}" -ResourceGroupName "${{inputs.resourceGroup}}"
           azPSVersion: '6.1.0'
       - name: Create / Update template spec
         uses: azure/powershell@v1
         with:
           inlineScript: |
            New-AzTemplateSpec -Name "${{inputs.specName}}" -Version "${{ steps.calculate.outputs.versionnumber }}" -ResourceGroupName "${{inputs.resourceGroup}}" -Location "westeurope" -TemplateFile ".\${{inputs.specFileName}}"
           azPSVersion: '6.1.0'