name: TemplateSpec - Internal VM
 
on:
  push:
    paths:
      - 'templatespec/azinternalvm/*'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep
          bicep --help
      - run:    bicep build ./templatespec/azinternalvm/azinternalvm.bicep   
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: ./**/*.json
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          format: ${major}.${minor}.${patch}-prerelease${increment}
          change_path: templatespec/azinternalvm
          bump_each_commit: true

 