name: Policy - All Policies
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'

env:
  Folder: './deploy'
  Scope: 'ManagementGroup'
  ScopeName: '324f7296-1869-4489-b11e-912351f38ead'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_MANAGEMENTGROUP }}
        enable-AzPSSession: true
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./scripts/azpolicy.ps1 -Scope "${{env.Scope}}" -ScopeName "${{env.ScopeName}}" -PolicyFolder "${{env.Folder}}"
        azPSVersion: "latest"
