name: manage-azure-policy-deploy_resource_locks_on_resource_groups_based_on_tags
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'
  push:
    paths:
      - 'policies/deploy_resource_locks_on_resource_groups_based_on_tags/**'
      - .github/workflows/manage-azure-policy-deploy_resource_locks_on_resource_groups_based_on_tags.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_MANAGEMENTGROUP}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/deploy_resource_locks_on_resource_groups_based_on_tags/**
