name: TS - Automation Account

on:
  push:
    paths:
      - 'templatespec/automationaccount/*'
      - .github/workflows/templatespec-automationaccount.yml
      - .module/log-analytics.bicep
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  specName: az-tempspec-automationaccount
  specfolder: './templatespec/automationaccount/automationaccount'
  specfilename: automationaccount.json
  resourcegroup: gaag-rg-templates

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: bicepbuild
        uses: ./.github/actions/buildbicep
        with:
          specFolder: ${{env.specfolder}}
          specName: ${{env.specName}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - id: deployspec
         uses: ./.github/actions/deploytemplatespec
         with:
           specFolder: ${{env.specfolder}}
           specName: ${{env.specName}}
           secret: ${{ secrets.AZURE_CREDENTIALS_MANAGEMENTGROUP }}
           resourceGroup: ${{env.resourcegroup}}
           specFileName : ${{env.specfilename}}
           clientId: ${{ secrets.AZURE_CLIENT_ID }}
           clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
           tenantId: ${{ secrets.AZURE_TENANT_ID }}
           azureSubscription: 5b389701-0e47-4738-b4fe-ddb67ac3a036
