name: TS - Automation Account

on:
  push:
    paths:
      - 'templatespec/automationaccount/*'
      - .github/workflows/templatespec-automationaccount.yml
      - .module/log-analytics.bicep
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  specName: az-tempspec-automationaccount
  specfolder: './templatespec/automationaccount/automationaccount'
  specfilename: automationaccount.json
  resourcegroup: gaag-rg-templates

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/buildbicep
        with:
          specFolder: ${{env.specfolder}}
          specName: ${{env.specName}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
       - uses: actions/download-artifact@v2
         name: Download template spec
         with:
             name: ${{env.specName}}
       - uses: actions/download-artifact@v2
         name: Download utility scripts
         with:
             name: ps-${{env.specName}}
       - name: Azure Login
         uses: Azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS_MANAGEMENTGROUP }}
           enable-AzPSSession: true
       - name: Check versionnumber
         uses: azure/powershell@v1
         id: calculate
         with:
           inlineScript: |
              .\Get-TemplateSpecVersion.ps1 -TemplateSpecName "${{env.specName}}" -ResourceGroupName "${{env.resourcegroup}}"
           azPSVersion: '6.1.0'
       - name: Create / Update template spec
         uses: azure/powershell@v1
         with:
           inlineScript: |
            New-AzTemplateSpec -Name "${{env.specName}}" -Version "${{ steps.calculate.outputs.versionnumber }}" -ResourceGroupName "${{env.resourcegroup}}" -Location "westeurope" -TemplateFile ".\${{env.specfilename}}"
           azPSVersion: '6.1.0'
